# Generated by Django 6.0 on 2025-12-19 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_newslettersubscriber_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 19, 11, 47, 28, 835556, tzinfo=datetime.timezone.utc)),
        ),
    ]
